#!/usr/bin/env python3
"""Materialize the single NextLat-only CFS-1 branch template.

The file is a parsed copy of the audited H3 NextLat adaptation configuration,
with only CFS-1's new intervention controls changed.  It is deliberately
*unbound*: ``run_cfs1_matrix.py`` must supply a hashed episode/arm bank at
launch.  A direct launch therefore names an impossible input instead of
silently training on a base corpus or a retired H3 bank.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import pathlib
import sys
from typing import Any

import yaml


REPO = pathlib.Path(__file__).resolve().parents[1]
SOURCE = REPO / "configs" / "adapt_near.yaml"
TARGET = REPO / "configs" / "cfs1_nextlat_adapt.yaml"
CFS1_STEPS = 500
CFS1_RECOVERY_INTERVAL = 50
CFS1_PARENT_SEEDS = [1234, 1235, 1236, 1237, 1238, 2234, 2235, 2236]
UNBOUND_BANK = "/content/cfs1/UNBOUND_CFS1_UPDATE_BANK_FORBIDDEN.txt"


class CFS1ConfigError(RuntimeError):
    pass


def _sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build() -> dict[str, Any]:
    if not SOURCE.is_file():
        raise CFS1ConfigError(f"missing audited NextLat adaptation source: {SOURCE}")
    source = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    if not isinstance(source, dict):
        raise CFS1ConfigError("audited adaptation source is not a YAML object")
    cfg = copy.deepcopy(source)
    trainer = cfg.get("trainer")
    data = cfg.get("data")
    model = cfg.get("model")
    if not all(isinstance(block, dict) for block in (trainer, data, model)):
        raise CFS1ConfigError("audited adaptation source lacks trainer/data/model blocks")
    if cfg.get("use_nextlat") is not True or cfg.get("use_bst") is not False:
        raise CFS1ConfigError("CFS-1 must start from the NextLat-only adaptation template")

    trainer.update({
        "train_batches": CFS1_STEPS,
        "save_recovery_checkpoint": CFS1_RECOVERY_INTERVAL,
        "out_dir": "/content/cfs1/UNBOUND_OUTPUT_FORBIDDEN",
        "experiment_name": "cfs1-unbound",
        "init_from": "resume",
        "compile": False,
        "log_to_wandb": False,
    })
    # The runner must replace BOTH values with the same verified per-arm bank.  This keeps
    # incidental trainer validation from importing a second, unbound population.
    data["stargraph_train_data_path"] = UNBOUND_BANK
    data["stargraph_test_data_path"] = UNBOUND_BANK
    model.update({"lambda_mse": 0.0, "lambda_kl": 0.0, "lambda_ce": 0.0})
    cfg["use_nextlat"] = True
    cfg["use_bst"] = False
    cfg["provenance"] = {
        "generator": "scripts/materialize_cfs1_configs.py",
        "source": "configs/adapt_near.yaml",
        "source_sha256": _sha256(SOURCE),
        "contract": "cfs1_full_parameter_next_token_ce_v1",
        "note": (
            "CFS-1 is a new NextLat-only, construction-matched causal-forgetting "
            "experiment. The runner injects the sole hashed update bank; this template "
            "must never be launched unbound."
        ),
    }
    cfg["cfs1"] = {
        "schema": "nextlat_forgetting/cfs1_config/1",
        "adaptation_steps": CFS1_STEPS,
        "parent_seeds": CFS1_PARENT_SEEDS,
        "episodes": [0, 1],
        "recovery_interval": CFS1_RECOVERY_INTERVAL,
        "full_parameter": True,
        "loss": "teacher_forced_next_token_cross_entropy",
        "unbound_bank_sentinel": UNBOUND_BANK,
    }
    return cfg


def render() -> str:
    payload = yaml.safe_dump(build(), sort_keys=False, allow_unicode=False)
    header = (
        "# GENERATED by scripts/materialize_cfs1_configs.py -- do not hand-edit.\n"
        "# Verify: .venv/bin/python scripts/materialize_cfs1_configs.py --check\n"
        "# The CFS-1 runner must replace UNBOUND_CFS1_UPDATE_BANK_FORBIDDEN with one\n"
        "# manifest-hashed episode/arm bank before every launch.\n"
    )
    return header + payload


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=pathlib.Path, default=TARGET)
    args = parser.parse_args(argv)
    expected = render()
    output = args.output.resolve()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"CFS-1 config is stale: regenerate {output}")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
